language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
    - pip install -r requirements.txt"
    - pip install -U nose2 codecov cov-core coverage

script: make coverage
after_success: codecov